version: "3.7"

services:
  db:
    image: postgres
    container_name: basePg
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=challenge
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: pebmed_challenge
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - db
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
